name: Checks

on:
    push:
        branches: ["gh-pages"]
    pull_request:
        branches: ["gh-pages"]
    workflow_dispatch:

jobs:
    checks:
        runs-on: ubuntu-22.04
        steps:
            - name: Check out the repository
              uses: actions/checkout@v6
